// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package stringui

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed assets/app_icon.png
var resourceAppiconPngData []byte
var resourceAppiconPng = &fyne.StaticResource{
	StaticName:    "assets/app_icon.png",
	StaticContent: resourceAppiconPngData,
}
